name: Million-App-Base-AutoBuilder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 第一步：把你的 Base64 字符串变回真实的 jks 文件，放在根目录
      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > release-key.jks

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # 第二步：开始打包，并把保险箱里的密码传给 Gradle
      - name: Build Android App
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SQL-Formatter-Pro-APK
          path: app/build/outputs/apk/release/*.apk
